apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-persistent-volume  
  labels:
    type: local  
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/"
---
